### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by OniryxRomainMarbaix** [artemnih/ngx-explorer#54]
Hi there, 👋

I tried your component with a custom service linked to my **very slow** backend and I got this error/crash when loading my page.
![image](https://user-images.githubusercontent.com/94960142/167433250-5637245c-6849-4adb-b980-2786cf12fceb.png)
![image](https://user-images.githubusercontent.com/94960142/167433426-9b11e397-527a-4704-980b-777f85cf58c3.png)

This can be reproduced with this method in the DataService : 
```
export class ExampleFileService implements IDataService<MyNode> {

  // ...

  getNodeChildren(node: MyNode): Observable<NodeContent<MyNode>> {
    return of({
      leafs: [],
      nodes: []
    })
    .pipe(delay(1200)); // Slow backend
  }

  // ...

}
```

Feel free to contact me. :-)

**Comment by artemtek** [comment]
@OniryxRomainMarbaix thanks for finding and fixing the issue
